version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_enem
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=enem_db
      - MYSQL_USER=enem_user
      - MYSQL_PASSWORD=secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
