-- esse codigo eu preferi inserir para criar manualmente a tabela no workbench por questões de praticidade, o codigo aqui serve para referencia.
USE enem_db;

CREATE TABLE DIM_ALUNO (
  ID_ALUNO INT PRIMARY KEY,
  TP_SEXO VARCHAR(1),
  TP_COR_RACA INT
);

CREATE TABLE DIM_ESCOLA (
  ID_ESCOLA INT PRIMARY KEY,
  CO_ESCOLA BIGINT,
  NO_ESCOLA VARCHAR(255),
  TP_DEPENDENCIA_ADM_ESC INT
);

CREATE TABLE FATO_NOTAS_ENEM (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FK_ALUNO INT,
  FK_ESCOLA INT,
  NU_NOTA_CN FLOAT,
  NU_NOTA_CH FLOAT,
  NU_NOTA_LC FLOAT,
  NU_NOTA_MT FLOAT,
  NU_NOTA_REDACAO FLOAT,
  TP_PRESENCA_CN TINYINT,
  TP_PRESENCA_CH TINYINT,
  TP_PRESENCA_LC TINYINT,
  TP_PRESENCA_MT TINYINT
);
